version: "2"
# Elasticsearch stack designed for container-native deployment
# using the Autopilot pattern

services:
  # ---------------------------------------------------
  # Consul as a service discovery tier
  # Should point to the autopilot/consul docker image?
  consul:
    image: mterron/consul-autopilot
    labels:
      - triton.cns.services=consul
    restart: always
    mem_limit: 128m
    ports:
      - 53
      - 8300
      - 8301
      - 8302
      - 8400
      - 8500
      - 8501
    env_file: _env_consul

  fabio:
    image: mterron/fabiolb
    restart: always
    mem_limit: 128m
    ports:
      - 9998
      - 9999
    dns:
      - 172.19.0.2
      - 8.8.8.8
    dns_search:
      - service.consul
      - node.consul
    env_file: _env_consul
    depends_on:
      - consul
  # ---------------------------------------------------
  # The logstash container is the target of Docker log drivers
  logstash:
    image: mterron/logstash-autopilot:latest
    mem_limit: 256m
    restart: always
    labels:
      - triton.cns.services=logstash
    depends_on:
      - elasticsearch-master
    ports:
      - 5140
      - "5140/udp"
    dns:
      - 172.19.0.2
      - 8.8.8.8
    dns_search:
      - service.consul
      - node.consul
    env_file: _env
    ports:
      - 9200
      - 9300

  # The kibana container
  kibana:
    image: mterron/kibana-autopilot:latest
    mem_limit: 256m
    restart: always
    labels:
      - triton.cns.services=logstash
    depends_on:
      - logstash
    ports:
      - 5601
    dns:
      - 172.19.0.2
      - 8.8.8.8
    dns_search:
      - service.consul
      - node.consul
    env_file: _env


  # ---------------------------------------------------
  # The master-only node serves as the coordinator of the cluster only
  elasticsearch-master:
    extends:
      file: ES.yml
      service: elasticsearch
    labels:
      - triton.cns.services=elasticsearch-master
    depends_on:
      - consul
    environment:
      - ES_SERVICE_NAME=elasticsearch-master
      - ES_NODE_MASTER=true
      - ES_NODE_DATA=false

  # ---------------------------------------------------
  # Data nodes hold data and perform data related operations such as CRUD, 
  # search, and aggregations.
  elasticsearch-data:
    extends:
      file: ES.yml
      service: elasticsearch
    labels:
      - triton.cns.services=elasticsearch-data
    depends_on:
      - elasticsearch-master
    environment:
      - ES_SERVICE_NAME=elasticsearch-data
      - ES_NODE_MASTER=false
      - ES_NODE_DATA=true

  # ---------------------------------------------------
  # Client nodes behaves as a “smart router” and is used to forward 
  # cluster-level requests to the master node and data-related 
  # requests (such as search) to the appropriate data nodes
  # elasticsearch-client:
  #   extends:
  #     file: ES.yml
  #     service: elasticsearch
  #   labels:
  #     - triton.cns.services=elasticsearch-client
  #   depends_on:
  #     - elasticsearch-master
  #   ports:
  #     - 9200
  #     - 9300
  #   environment:
  #     - ES_SERVICE_NAME=elasticsearch-client
  #     - ES_NODE_MASTER=false
  #     - ES_NODE_DATA=false
