version: "2"
# Elasticsearch stack designed for container-native deployment
# using the Autopilot pattern

services:
  # ---------------------------------------------------
  # This common service definition is the default for nodes that both store
  # data and act as potential masternodes. It also serves as a template for
  # master-only, data-only and client ES nodes.
  elasticsearch:
    image: mterron/elasticsearch-autopilot
    labels:
      - triton.cns.services=elasticsearch-master
    mem_limit: 256m
    restart: always
    ulimits:
        memlock: 9223372036854775807
    dns:
      - 172.19.0.2
      - 8.8.8.8
    dns_search:
      - service.consul
      - node.consul
    env_file: _env
    environment:
      - ES_SERVICE_NAME=elasticsearch-master
      - ES_NODE_MASTER=true
      - ES_NODE_DATA=true
